---
- name: "generate /etc/hosts.ansible file"
  become: yes
  template:
    src: templates/hosts.j2
    dest: '/etc/hosts'
    owner: root
    group: root
    mode: 0644

- name: "run the SHA1 enable"
  become: yes
  shell : update-crypto-policies --set DEFAULT:SHA1
