---
- name: download {{ url }}
  run_once: true
  get_url:
    url: "{{ url }}"
    dest: "/tmp/{{ file }}"

- name: extract /tmp/{{ file }}
  become: yes
  unarchive:
    src: "/tmp/{{ file }}"
    dest: /usr/local
    copy: no
    owner: root
    group: root
    creates: "{{ kafka_home }}"

- name: link to /usr/local/kafka
  become: yes
  file:
    src:  "{{ kafka_home }}"
    dest: /usr/local/kafka
    state: link

- name: set PATH=$PATH:{{ kafka_home }}/bin
  become: yes
  lineinfile:
    dest: /etc/profile.d/kafka.sh
    create: yes
    state: present
    regexp: '^PATH'
    line: 'PATH=$PATH:{{ kafka_home }}/bin'

# - import_tasks: zookeeper.yml
#   tags: zookeeper

- import_tasks: kafka.yml
  tags: kafka
