---
- name: download {{ url }}
  run_once: true
  get_url:
    url: "{{ url }}"
    dest: "/tmp/{{ file }}"

- name: extract /tmp/{{ file }}
  become: yes
  unarchive:
    src: "/tmp/{{ file }}"
    dest: /usr/local
    copy: no
    creates: "{{ prometheus_home }}"
  notify: restart prometheus

- name: set ownership on {{ prometheus_home }}
  become: yes
  file:
    path: "{{ prometheus_home }}"
    owner: ec2-user
    group: ec2-user
    recurse: yes
    mode: 0755

- name: copy prometheus.yml to {{ prometheus_home }}/prometheus.yml
  template:
    src: templates/prometheus.yml.j2
    dest: "{{ prometheus_home }}/prometheus.yml"
  notify: restart prometheus

- name: install prometheus systemd unit file
  become: yes
  template:
    src: templates/prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: restart prometheus
